### ISSUE TITLE
运行text_grapher.py出错

### ISSUE THREAD

**Issue by gaohanga** [liuhuanyong/TextGrapher#15]
Traceback (most recent call last):
  File "D:\github\text\TextGrapher-master\text_grapher.py", line 225, in <module>
    handler = CrimeMining()
  File "D:\github\text\TextGrapher-master\text_grapher.py", line 17, in __init__
    self.parser = LtpParser()
  File "D:\github\text\TextGrapher-master\sentence_parser.py", line 12, in __init__
    self.segmentor = Segmentor()
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)

Invoked with: 
请问这是什么原因

**Comment by lili1234567890** [comment]
> Traceback (most recent call last): File "D:\github\text\TextGrapher-master\text_grapher.py", line 225, in handler = CrimeMining() File "D:\github\text\TextGrapher-master\text_grapher.py", line 17, in **init** self.parser = LtpParser() File "D:\github\text\TextGrapher-master\sentence_parser.py", line 12, in **init** self.segmentor = Segmentor() TypeError: **init**(): incompatible constructor arguments. The following argument types are supported: 1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)
> 
> Invoked with: 请问这是什么原因

我也是这个问题，想请问一下你解决了吗，是如何解决的呢？

**Comment by yellowmamba824** [comment]
me too

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！

**Comment by jyyang621** [comment]
我也是这个错误

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！

**Comment by coco1230** [comment]
pyltp的版本问题

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！
